# Generated by Django 5.0.4 on 2024-07-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangbeli',
            name='jumlah',
            field=models.BigIntegerField(),
        ),
    ]
