# Generated by Django 5.0.4 on 2024-07-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_barangbeli_jenis'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangbeli',
            name='jenis',
            field=models.CharField(choices=[('Dana', 'Dana'), ('Shoope Pay', 'Shoope Pay'), ('Ovo', 'Ovo')], default='Dana', max_length=20),
        ),
    ]
