# Generated by Django 5.0.4 on 2024-07-07 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_jenis_barangbeli_jenis_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barangbeli2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodeworld', models.CharField(max_length=10)),
                ('nama', models.CharField(max_length=50)),
                ('growid', models.CharField(max_length=8)),
                ('nomor', models.BigIntegerField()),
                ('jumlah', models.IntegerField()),
                ('jenis', models.CharField(choices=[('Dana', 'Dana'), ('Shoope Pay', 'Shoope Pay'), ('Ovo', 'Ovo')], default='Dana', max_length=20)),
                ('jenis_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.jenis')),
            ],
        ),
    ]
