# Generated by Django 5.0.4 on 2024-07-08 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_barangbeli2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barangjual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField()),
                ('nomor', models.BigIntegerField()),
                ('nama', models.CharField(max_length=50)),
                ('jenis', models.CharField(choices=[('Dana', 'Dana'), ('Shoope Pay', 'Shoope Pay'), ('Ovo', 'Ovo')], default='Dana', max_length=20)),
                ('nomor_rekening', models.BigIntegerField()),
                ('jenis_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.jenis')),
            ],
        ),
        migrations.DeleteModel(
            name='Barangbeli2',
        ),
    ]
