# Generated by Django 5.0.4 on 2024-07-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_barangjual_delete_barangbeli2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barangbeli',
            name='jenis',
        ),
        migrations.RemoveField(
            model_name='barangjual',
            name='jenis',
        ),
        migrations.AlterField(
            model_name='barangbeli',
            name='kodeworld',
            field=models.CharField(max_length=10, verbose_name='World'),
        ),
        migrations.AlterField(
            model_name='barangbeli',
            name='nomor',
            field=models.BigIntegerField(verbose_name='Nomor Rekening'),
        ),
    ]
