# Generated by Django 5.0.4 on 2024-07-16 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_remove_barangbeli_jenis_remove_barangjual_jenis_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barangbeli',
            old_name='jenis_id',
            new_name='pembayaran',
        ),
        migrations.RemoveField(
            model_name='barangjual',
            name='jenis_id',
        ),
        migrations.AddField(
            model_name='barangjual',
            name='pembayaran',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.jenis'),
        ),
    ]
