# Generated by Django 5.0.6 on 2024-07-18 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_rename_jenis_id_barangbeli_pembayaran_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangbeli',
            name='buktitransfer',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='barangjual',
            name='buktipengiriman',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
