# Generated by Django 5.0.6 on 2024-07-18 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_barangbeli_buktitransfer_barangjual_buktipengiriman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangbeli',
            name='buktitransfer',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Bukti Transfer'),
        ),
        migrations.AlterField(
            model_name='barangjual',
            name='buktipengiriman',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Bukti Pengiriman'),
        ),
    ]
