# Generated by Django 5.0.4 on 2024-07-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_barangbeli_buktitransfer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangbeli',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='barangjual',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
